### ISSUE TITLE
Diagramme de cas d'utilisation

### ISSUE THREAD

**Issue by ghoulaymen** [ZanzanaTeam/Wild-Fly-Delivery#1]

**Comment by NesrineCherif** [comment]
Draft :+1: 
-- Client :
* Ajouter les commandes avec spécifications. 
* Chercher par zone un/des restaurant(s).
* Choisir un/des restaurant(s).
* Choisir le lieu de la livraison de la commande.
* Annuler un/des commandes.
* Valider un/des commandes.
* Noter Restaurants.
* Noter commandes.
* Noter Commandes.
-- Responsable du restaurant :
* S'authenfier. -- include : avoir un compte Foursquare.
* Ajouter menus.
* Ajouter les prix des menus.
* Ajouter Zone de la livraison. 
* Ajouter les types des livraisons. 
* Gérer les commandes.

**Comment by medaymenjendoubi** [comment]
utiliser ce plugin UML designer : https://marketplace.eclipse.org/content/uml-designer

Installation : 
Help -> install new software -> add link (http://d80xfn34saixv.cloudfront.net/sirius2.0)
selectionée UML designer -> suivant -> install 

Merci :)
