### ISSUE TITLE
Entities Review

### ISSUE THREAD

**Issue by Samihkadri** [ZanzanaTeam/Wild-Fly-Delivery#14]
English Review 
Enumeration Review 
Minimum Price for Delivery attribute added

**Comment by medaymenjendoubi** [comment]
je pense qu'on va modifier les entités :( 

-  Compte Foursquare peut créer plusieurs endroit c-à-d l'entité *OWNER* peut avoir plusieurs Restaurant (idFoursquare)
- On va préciser les insertions/modification en cascade
